# Generated by Django 4.2.6 on 2024-01-03 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_comment_created_at'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
