# Generated by Django 4.2.6 on 2024-05-15 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_theme'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Theme',
        ),
    ]
